const dbData = {
  Categorias: [
    {
      id: "4d4b7104d754a06370d81259",
      name: "Arte y entretenimiento",
      pluralName: "Arte y entretenimiento",
      shortName: "Arte y entretenimiento",
      descripcion: "",
      imagenUrl:
        "https://st.hzcdn.com/simgs/0a6195030f395aab_4-5646/contemporary-home-theater.jpg",
      isActive: false,
      lugares: [
        {
          categoria: "Cine",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: ["Av. De los limones", "Benidorm Comunidad Valenciana"],
          distancia: 1257,
          fechaCreado: 1506372744346,
          id: "4bb354c842959c74afc4212c",
          isActive: true,
          isPremium: true,
          latitud: 38.539853043999784,
          longitud: -0.13340009169384148,
          nombre: "Cines Colci",
          poblacion: "España"
        },
        {
          categoria: "Parque de agua",
          ciudad: "Benidorm",
          descripcion:
            "Amplio parque temático inspirado en Grecia con una piscina de olas, toboganes de agua, tiendas y restaurantes.",
          direccion: "Foia del Verdader, 1, 03502 Benidorm, Alicante",
          distancia: 3428,
          fechaCreado: 1506372744350,
          id: "50278ad7e4b06553e27b8c64",
          isActive: true,
          isPremium: true,
          latitud: 38.567579470494636,
          longitud: -0.13958743283562336,
          nombre: "Aqua Natura",
          poblacion: "España"
        },
        {
          categoria: "Bar",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: [
            "Calle Gerona (Avenue Del Derramador)",
            "Benidorm Comunidad Valenciana"
          ],
          distancia: 3208,
          fechaCreado: 1506372744351,
          id: "4b65e785f964a5205a072be3",
          isActive: true,
          isPremium: true,
          latitud: 38.53694786178108,
          longitud: -0.11066534105338535,
          nombre: "Morgans Tavern",
          poblacion: "España"
        },
        {
          categoria: "Casino",
          ciudad: "Altea",
          descripcion: "",
          direccion: ["03590 Altea Comunidad Valenciana"],
          distancia: 15040,
          fechaCreado: 1506372744351,
          id: "578e108b498e779bc61d5621",
          isActive: true,
          isPremium: true,
          latitud: 38.6407532694094,
          longitud: -0.036155230307184046,
          nombre: "Don Hermans casa",
          poblacion: "España"
        },
        {
          categoria: "Lugar histórico",
          ciudad: "Alfaz del Pi",
          descripcion: "",
          direccion: ["Plaça Major", "03580 Alfaz del Pi Comunidad Valenciana"],
          distancia: 6131,
          fechaCreado: 1506372744352,
          id: "5254674f498ee4bdbd8658bd",
          isActive: true,
          isPremium: true,
          latitud: 38.5812851267536,
          longitud: -0.10493009878749313,
          nombre: "Plaça Major l'Alfàs del Pi",
          poblacion: "España"
        },
        {
          categoria: "Lugar histórico",
          ciudad: "Muchamiel",
          descripcion: "",
          direccion: ["Calle Oms", "03110 Muchamiel Comunidad Valenciana"],
          distancia: 29755,
          fechaCreado: 1506372744353,
          id: "4e9ef1da93ad5d11f3c6a92b",
          isActive: true,
          isPremium: true,
          latitud: 38.40710830073134,
          longitud: -0.44561902014992405,
          nombre: "Urbanizacion Los Jardines.",
          poblacion: "España"
        },
        {
          categoria: "Espacio para eventos",
          ciudad: "Muchamiel",
          descripcion: "",
          direccion: [
            "Avenida Carlos Soler 64",
            "03110 Muchamiel Comunidad Valenciana"
          ],
          distancia: 29253,
          fechaCreado: 1506372744354,
          id: "4e401aeb2271d21e871802d5",
          isActive: true,
          isPremium: true,
          latitud: 38.415497130281,
          longitud: -0.4448765516281128,
          nombre: "Centro Social José Bernabéu",
          poblacion: "España"
        },
        {
          categoria: "Lugar de música",
          ciudad: "Calpe",
          descripcion: "",
          direccion: ["Calpe Comunidad Valenciana"],
          distancia: 20298,
          fechaCreado: 1506372744356,
          id: "4ea1ee7de5facb29c70c4aa1",
          isActive: true,
          isPremium: true,
          latitud: 38.64465347194613,
          longitud: 0.041174050237217416,
          nombre: "Filà Moriscos",
          poblacion: "España"
        },
        {
          categoria: "Museo histórico",
          ciudad: "Villajoyosa",
          descripcion: "",
          direccion: [
            "Avda Pianista Gonzalo Soriano, 13",
            "03570 Villajoyosa Comunidad Valenciana"
          ],
          distancia: 7945,
          fechaCreado: 1506372744357,
          id: "4d2351dbf7a9a1435556479f",
          isActive: true,
          isPremium: true,
          latitud: 38.51235355833149,
          longitud: -0.23293049021151718,
          nombre: "Museo Del Chocolate Valor",
          poblacion: "España"
        },
        {
          categoria: "Museo histórico",
          ciudad: "Cocentaina",
          descripcion: "",
          direccion: ["Cocentaina Comunidad Valenciana"],
          distancia: 34219,
          fechaCreado: 1506372744358,
          id: "4beecb812c082d7f2adf3042",
          isActive: true,
          isPremium: true,
          latitud: 38.74293009196585,
          longitud: -0.4401612901785187,
          nombre: "Palau Comtal",
          poblacion: "España"
        },
        {
          categoria: "Centro comercial",
          ciudad: "Finestrat",
          descripcion: "",
          direccion: [
            "Avinguda del País Valencià 2",
            "03509 Finestrat Comunidad Valenciana"
          ],
          distancia: 2406,
          fechaCreado: 1506372744360,
          id: "4bd8e992efb2ef3b825fec9c",
          isActive: true,
          isPremium: true,
          latitud: 38.53889609288935,
          longitud: -0.1750718197244041,
          nombre: "Centro Comercial La Marina",
          poblacion: "España"
        },
        {
          categoria: "Autocine",
          ciudad: "Muchamiel",
          descripcion: "",
          direccion: ["C. Cerezo, s/n", "03110 Muchamiel Comunidad Valenciana"],
          distancia: 32619,
          fechaCreado: 1506372744361,
          id: "4c0bfb3ca1b32d7f9dd79bf0",
          isActive: true,
          isPremium: true,
          latitud: 38.407846572786696,
          longitud: -0.4832142396843525,
          nombre: "Autocine El Sur",
          poblacion: "España"
        },
        {
          categoria: "Ciudad",
          ciudad: "Alicante",
          descripcion: "",
          direccion: ["Alicante Comunidad Valenciana"],
          distancia: 29422,
          fechaCreado: 1506372744362,
          id: "4bac85a0f964a52023f93ae3",
          isActive: true,
          isPremium: true,
          latitud: 38.68792365230616,
          longitud: 0.1305398099345388,
          nombre: "Moraira",
          poblacion: "España"
        },
        {
          categoria: "Parque de agua",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: [
            "Parque Natural Sierra Helada",
            "03503 Benidorm Comunidad Valenciana"
          ],
          distancia: 4632,
          fechaCreado: 1506372744363,
          id: "4bc5fbcb6c26b7137215ecf3",
          isActive: true,
          isPremium: true,
          latitud: 38.54191040164317,
          longitud: -0.09461703186294232,
          nombre: "Parque Acuático Aqualandia",
          poblacion: "España"
        },
        {
          categoria: "Sala de conciertos",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: ["C/. Severo Ochoa", "Benidorm Comunidad Valenciana"],
          distancia: 4013,
          fechaCreado: 1506372744363,
          id: "4bcefed2c564ef3b6d0deff0",
          isActive: true,
          isPremium: true,
          latitud: 38.54438955464703,
          longitud: -0.10228728632645961,
          nombre: "Benidorm Palace",
          poblacion: "España"
        },
        {
          categoria: "Biblioteca universitaria",
          ciudad: "San Juan de Alicante",
          descripcion: "",
          direccion: [
            "Calle del Mar, 49-61",
            "03550 San Juan de Alicante Comunidad Valenciana"
          ],
          distancia: 29043,
          fechaCreado: 1506372744364,
          id: "4bf81d725ec320a19a2688d3",
          isActive: true,
          isPremium: true,
          latitud: 38.40219194682822,
          longitud: -0.43250561974993323,
          nombre: "Casa de la Cultura de Sant Joan",
          poblacion: "España"
        },
        {
          categoria: "Club de rock",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: ["playa levante", "03503 Benidorm Comunidad Valenciana"],
          distancia: 2046,
          fechaCreado: 1506372744366,
          id: "4d1a018985fc6dcb0104c24e",
          isActive: true,
          isPremium: true,
          latitud: 38.535905221680565,
          longitud: -0.12407858276143627,
          nombre: "Heartbreak American Bar",
          poblacion: "España"
        },
        {
          categoria: "Lugar de artes interpretativas",
          ciudad: "Calpe",
          descripcion: "",
          direccion: ["Calpe Comunidad Valenciana"],
          distancia: 20416,
          fechaCreado: 1506372744366,
          id: "4e317532a809ef7b4ecd5f5a",
          isActive: true,
          isPremium: true,
          latitud: 38.64319310018572,
          longitud: 0.04416901162121661,
          nombre: "Casa de la Cultura de Calpe",
          poblacion: "España"
        },
        {
          categoria: "Parque temático",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: [
            "Ctra. Benidorm a Finestrat (Camino del Morales)",
            "03502 Benidorm Comunidad Valenciana"
          ],
          distancia: 2676,
          fechaCreado: 1506372744368,
          id: "4ba4e617f964a5208dc038e3",
          isActive: true,
          isPremium: true,
          latitud: 38.559763368347305,
          longitud: -0.15881381508666523,
          nombre: "Terra Mítica",
          poblacion: "España"
        },
        {
          categoria: "Multicine",
          ciudad: "Cocentaina",
          descripcion: "",
          direccion: [
            "Centro Comercial L'Altet",
            "03820 Cocentaina Comunidad Valenciana"
          ],
          distancia: 33560,
          fechaCreado: 1506372744369,
          id: "4c7808b681bca093afb4f814",
          isActive: true,
          isPremium: true,
          latitud: 38.731690276870516,
          longitud: -0.4426288604736328,
          nombre: "Cines L'Altet",
          poblacion: "España"
        },
        {
          categoria: "Club de rock",
          ciudad: "Alicante",
          descripcion: "",
          direccion: [
            "Av de la Costa Blanca, 128",
            "03540 Alicante Comunidad Valenciana"
          ],
          distancia: 29850,
          fechaCreado: 1506372744370,
          id: "4c76cf4359a3236aeacdbf18",
          isActive: true,
          isPremium: true,
          latitud: 38.36689169673129,
          longitud: -0.41177283692313416,
          nombre: "Harley's Pub",
          poblacion: "España"
        },
        {
          categoria: "Zoológico",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: [
            "Partida Foia Del Verdader, 1",
            "03502 Benidorm Comunidad Valenciana"
          ],
          distancia: 3574,
          fechaCreado: 1506372744370,
          id: "4bed05ca1059d13a79d951d8",
          isActive: true,
          isPremium: true,
          latitud: 38.56920661305151,
          longitud: -0.14179229736328125,
          nombre: "Terra Natura",
          poblacion: "España"
        },
        {
          categoria: "Zoológico",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: [
            "C/. Sierra Helada s/n",
            "03503 Benidorm Comunidad Valenciana"
          ],
          distancia: 4717,
          fechaCreado: 1506372744371,
          id: "4bd5a1405631c9b6a35ca430",
          isActive: true,
          isPremium: true,
          latitud: 38.54268125634862,
          longitud: -0.09374518169248688,
          nombre: "Mundomar Benidorm",
          poblacion: "España"
        }
      ]
    },
    {
      id: "4d4b7105d754a06374d81259",
      name: "Comida",
      pluralName: "Comida",
      shortName: "Comida",
      descripcion: "",
      imagenUrl: "",
      isActive: false,
      lugares: [
        {
          categoria: "Restaurante de tapas",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: [
            "Plaza de la Constitución, 2",
            "03503 Benidorm Comunidad Valenciana"
          ],
          distancia: 1473,
          fechaCreado: 1506374163191,
          id: "4ae60b24f964a52049a421e3",
          isActive: true,
          isPremium: true,
          latitud: 38.53540616464432,
          longitud: -0.13077348661886562,
          nombre: "La Cava Aragonesa",
          poblacion: "España"
        },
        {
          categoria: "Marisquería",
          ciudad: "Benidorm",
          descripcion: "",
          direccion: [
            "P. de La Carretera, 16",
            "03503 Benidorm Comunidad Valenciana"
          ],
          distancia: 1506,
          fechaCreado: 1506374163194,
          id: "4cceacdbee23a143ca3e2da8",
          isActive: true,
          isPremium: true,
          latitud: 38.53671490544539,
          longitud: -0.1302248353292555,
          nombre: "La Mejillonera",
          poblacion: "España"
        },
        {
          categoria: "Restaurante de paella",
          ciudad: "Benissa",
          descripcion: "",
          direccion: [
            "Av. Calcides Benimarco s/n",
            "03720 Benissa Comunidad Valenciana"
          ],
          distancia: 26982,
          fechaCreado: 1506374163195,
          id: "4c93b67772dd224ba9389391",
          isActive: true,
          isPremium: true,
          latitud: 38.696887398389116,
          longitud: 0.08610769618015784,
          nombre: "Restaurante Cañis",
          poblacion: "España"
        },
        {
          categoria: "Café",
          ciudad: "Alfaz del Pi",
          descripcion: "",
          direccion: ["03581 Alfaz del Pi Comunidad Valenciana"],
          distancia: 7378,
          fechaCreado: 1506374163198,
          id: "59c3d4329b047301ccf87cef",
          isActive: true,
          isPremium: true,
          latitud: 38.572117,
          longitud: -0.075298,
          nombre: "Rara Cafe-Bar",
          poblacion: "España"
        },
        {
          categoria: "Cafetería",
          ciudad: "San Vicente",
          descripcion: "",
          direccion: [
            "Calle Denia 5",
            "03690 San Vicente Comunidad Valenciana"
          ],
          distancia: 35897,
          fechaCreado: 1506374163198,
          id: "5707f89b498eb339e90a1595",
          isActive: true,
          isPremium: true,
          latitud: 38.40247036979747,
          longitud: -0.5215877294540405,
          nombre: "Batoi Café Bar",
          poblacion: "España"
        },
        {
          categoria: "Restaurante mediterráneo",
          ciudad: "Moraira",
          descripcion: "",
          direccion: ["Moraira Comunidad Valenciana"],
          distancia: 28874,
          fechaCreado: 1506374163199,
          id: '4bb7823598c7ef3b0ddf2f02',
          isActive: true,
          isPremium: true,
          latitud: 38.685255586503054,
          longitud: 0.1252452891556986,
          nombre: 'El Chamizo',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante de comida rápida',
          ciudad: 'Calpe',
          descripcion: '',
          direccion: ['Playa el Arenal', 'Calpe Comunidad Valenciana'],
          distancia: 21301,
          fechaCreado: 1506374163200,
          id: '4bebf500a9900f4704591840',
          isActive: true,
          isPremium: true,
          latitud: 38.64201838505604,
          longitud: 0.05749235307380417,
          nombre: 'Morena Resto Bar & Cocktails',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante español',
          ciudad: 'Altea',
          descripcion: '',
          direccion: [
            'Calle del Portal Viejo, 17-19',
            '03590 Altea Comunidad Valenciana'
          ],
          distancia: 10869,
          fechaCreado: 1506374163204,
          id: '4d3b42d6bf6d5481dd55d5e1',
          isActive: true,
          isPremium: true,
          latitud: 38.599791783258475,
          longitud: -0.051430970344623156,
          nombre: 'Xef Pirata',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante mediterráneo',
          ciudad: 'Calp / Calpe',
          descripcion: '',
          direccion: ['03710 Calp / Calpe Comunidad Valenciana'],
          distancia: 22539,
          fechaCreado: 1506374163205,
          id: '4debf5c852b11677f0635126',
          isActive: true,
          isPremium: true,
          latitud: 38.644178429017636,
          longitud: 0.07259231293446385,
          nombre: 'Sabores y Copas 78',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante español',
          ciudad: 'Calpe',
          descripcion: '',
          direccion: [
            'Urbanización la Canuta Baja, 35b',
            '03710 Calpe Comunidad Valenciana'
          ],
          distancia: 19138,
          fechaCreado: 1506374163206,
          id: '4fa9a2f5e4b096d47090a405',
          isActive: true,
          isPremium: true,
          latitud: 38.635377,
          longitud: 0.033238,
          nombre: 'Restaurante Puerto Blanco',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante',
          ciudad: 'Moraira',
          descripcion: '',
          direccion: ['Moraira Comunidad Valenciana'],
          distancia: 29857,
          fechaCreado: 1506374163209,
          id: '4bcde8db0687ef3b21b1e1cc',
          isActive: true,
          isPremium: true,
          latitud: 38.68731380663424,
          longitud: 0.13712910720022867,
          nombre: 'Club Náutico de Moraira',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante de comida rápida',
          ciudad: 'Calpe',
          descripcion: '',
          direccion: [
            'Avenida de los Ejércitos Españoles, s/n',
            'Calpe Comunidad Valenciana'
          ],
          distancia: 21229,
          fechaCreado: 1506374163209,
          id: '557d8d0d498e5a5e79c411ea',
          isActive: true,
          isPremium: true,
          latitud: 38.64453902084822,
          longitud: 0.05435516020215878,
          nombre: 'McDonalds',
          poblacion: 'España'
        },
        {
          categoria: 'Pizzería',
          ciudad: 'Altea',
          descripcion: '',
          direccion: [
            'Carrer Major 14 (Carrer Salamanca)',
            'Altea Comunidad Valenciana'
          ],
          distancia: 10878,
          fechaCreado: 1506374163210,
          id: '4c3ef10d51dee21e5b3eeb6e',
          isActive: true,
          isPremium: true,
          latitud: 38.599562892749205,
          longitud: -0.05106301373478296,
          nombre: 'El Castell',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante de comida rápida',
          ciudad: 'Calpe',
          descripcion: '',
          direccion: [
            'Cc Plaza Central-6079 Avenida Diputacion',
            '3710 Calpe Comunidad Valenciana'
          ],
          distancia: 20923,
          fechaCreado: 1506374163211,
          id: '4bd1f8309854d13afea5fa4d',
          isActive: true,
          isPremium: true,
          latitud: 38.64557411076006,
          longitud: 0.04916441685026662,
          nombre: 'Burger King',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante',
          ciudad: 'Moraira',
          descripcion: '',
          direccion: ['Moraira Comunidad Valenciana'],
          distancia: 29564,
          fechaCreado: 1506374163212,
          id: '4c795d8c3badb1f79ad04e54',
          isActive: true,
          isPremium: true,
          latitud: 38.68704727384022,
          longitud: 0.13329446728750005,
          nombre: 'Eleven',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante español',
          ciudad: 'Benissa',
          descripcion: '',
          direccion: [
            'Ctra Calp-Moraira km 2 (Club Náutico Les Bassetes)',
            '03720 Benissa Comunidad Valenciana'
          ],
          distancia: 24342,
          fechaCreado: 1506374163213,
          id: '4f918ba56b747fc20fcf223a',
          isActive: true,
          isPremium: true,
          latitud: 38.659015493293275,
          longitud: 0.085032828564849,
          nombre: 'CORAL BEACH Les Bassetes',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante mediterráneo',
          ciudad: 'Altea',
          descripcion: '',
          direccion: [
            'Puerto Deportivo Luis Campomanes',
            '03599 Altea Comunidad Valenciana'
          ],
          distancia: 16271,
          fechaCreado: 1506374163214,
          id: '4fef0d76f13675b4acb2dd33',
          isActive: true,
          isPremium: true,
          latitud: 38.63030209934969,
          longitud: -0.003130847438453223,
          nombre: 'Saltea Restaurante',
          poblacion: 'España'
        },
        {
          categoria: 'Gastropub',
          ciudad: '',
          descripcion: '',
          direccion: '',
          distancia: 21318,
          fechaCreado: 1506374163215,
          id: '53624ac8498e1549344550b7',
          isActive: true,
          isPremium: true,
          latitud: 38.64211804291388,
          longitud: 0.057641918740815076,
          nombre: 'Iguana Beach',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante mediterráneo',
          ciudad: 'Benissa',
          descripcion: '',
          direccion: [
            'Cala de la Fustera s/n',
            '03720 Benissa Comunidad Valenciana'
          ],
          distancia: 24917,
          fechaCreado: 1506374163216,
          id: '5370f893498e8121823da2b9',
          isActive: true,
          isPremium: true,
          latitud: 38.664996392049666,
          longitud: 0.08783335310492488,
          nombre: 'Mandala Beach Bar & Restaurant',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante',
          ciudad: 'Calpe',
          descripcion: '',
          direccion: ['Calpe Comunidad Valenciana'],
          distancia: 20795,
          fechaCreado: 1506374163217,
          id: '4e5692051838c793c079b348',
          isActive: true,
          isPremium: true,
          latitud: 38.64206983017669,
          longitud: 0.050458530324219694,
          nombre: 'Restaurante Capri',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante',
          ciudad: 'Calpe',
          descripcion: '',
          direccion: [
            'Paseo Maritimo Arenal Edificio Caribe Playa',
            'Calpe Comunidad Valenciana'
          ],
          distancia: 20743,
          fechaCreado: 1506374163218,
          id: '5358d54d498ec14dda53eb18',
          isActive: true,
          isPremium: true,
          latitud: 38.64204097466115,
          longitud: 0.049765716352701536,
          nombre: 'El Chiringuito Restaurant',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante italiano',
          ciudad: 'Moraira',
          descripcion: '',
          direccion: [
            'Avd de la Paz 22',
            '03724 Moraira Comunidad Valenciana'
          ],
          distancia: 29493,
          fechaCreado: 1506374163219,
          id: '4fca7360e4b02645582aef7d',
          isActive: true,
          isPremium: true,
          latitud: 38.6875423989883,
          longitud: 0.13187149496374687,
          nombre: 'vespa\'s',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante',
          ciudad: 'Alicante',
          descripcion: '',
          direccion: [
            'Av. Historiador Vicente Ramos, s/n',
            '03540 Alicante Comunidad Valenciana'
          ],
          distancia: 31214,
          fechaCreado: 1506374163220,
          id: '4e20c2921838712abe6a9c3c',
          isActive: true,
          isPremium: true,
          latitud: 38.36599094506525,
          longitud: -0.4308625652140046,
          nombre: 'Mauro & Sensai',
          poblacion: 'España'
        },
        {
          categoria: 'Restaurante de comida rápida',
          ciudad: 'Benidorm',
          descripcion: '',
          direccion: [
            'Avenida Alcoy Edf.Principado A',
            '3500 Benidorm Comunidad Valenciana'
          ],
          distancia: 1809,
          fechaCreado: 1506374163221,
          id: '4de8002352b1741cdaf7be05',
          isActive: true,
          isPremium: true,
          latitud: 38.53563433788841,
          longitud: -0.1268513840030087,
          nombre: 'Burger King',
          poblacion: 'España'
        },
        {
          categoria: 'Café',
          ciudad: 'Alicante',
          descripcion: '',
          direccion: [
            'Bulevard de los Músicos, 21',
            '03581 Alicante Comunidad Valenciana'
          ],
          distancia: 8155,
          fechaCreado: 1506374163221,
          id: '522847418bbda2b54007c167',
          isActive: true,
          isPremium: true,
          latitud: 38.574340518357786,
          longitud: -0.06659993772787619,
          nombre: 'D·Origen Coffee Roasters',
          poblacion: 'España'
        }
      ]
    },
    {
      id: '4d4b7105d754a06376d81259',
      name: 'Local nocturno',
      pluralName: 'Locales nocturnos',
      shortName: 'Nocturna',
      descripcion: '',
      imagenUrl: '',
      isActive: false
    },
    {
      id: '4d4b7105d754a06378d81259',
      name: 'Tienda y servicio',
      pluralName: 'Tiendas y servicios',
      shortName: 'Tiendas',
      descripcion: '',
      imagenUrl: '',
      isActive: false
    },
    {
      id: '4d4b7105d754a06379d81259',
      name: 'Viajes y Transporte',
      pluralName: 'Viajes y Transporte',
      shortName: 'Viajes',
      descripcion: '',
      imagenUrl: '',
      isActive: false
    }
  ]
}
